#!/usr/bin/env bash

#### Error detector
set -euo pipefail
trap 'printf "\n\033[1;33mOps! \033[1;31m\b Something went wrong! \n\033[1;34mExiting...\033[0m\n" && exit 1' INT TERM ERR
#### Importing libraries
source lib/colors
source lib/wait_with_spinner_loading
source lib/progress_bar_by_task_completion
#### Code Bellow

if [ "$(whoami)" != "root" ]; then
    echo -e "You're not root! Exiting..."
    exit 1
fi

# == Primordial Dependencies ==
SUDO=$(command -v sudo 2>/dev/null || true)

$SUDO apt-get update &>/dev/null &
wait_with_spinner_loading "Updating system..."

$SUDO apt-get full-upgrade -y &>/dev/null &
wait_with_spinner_loading "Upgrading system..."

source sources/essentials.list

$SUDO apt-get install --fix-broken --fix-missing -y ${packages[@]} 1>/dev/null &
wait_with_spinner_loading "Installing Basic Dependencies..."

while true; do
    read -p "Do you want to install extra dependencies that might be usefull for you? (y/n): " ANSWER
    case $ANSWER in
    [Yy] | [Yy][Ee][Ss])
        source sources/extra_essential.list
        $SUDO apt-get install --fix-broken --fix-missing -y ${extra_packages[@]} #1>/dev/null &
        #wait_with_spinner_loading "Installing Extra Dependencies..."
        break
        ;;
    [Nn] | [Nn][Oo])
        echo "Skipping Extra Dependencies installation."
        break
        ;;
    *)
        echo "Invalid answer. Please enter 'y' for yes or 'n' for no."
        ;;
    esac
done

sudo apt-get autopurge -y
sudo apt-get clean
# == Primordial Dependencies ==

# == Ondřej Surý PHP Repository for Debian ==
while true; do
    read -p "Do you want to install PHP and related packages? (y/n): " ANSWER
    case $ANSWER in
    [Yy] | [Yy][Ee][Ss])
        echo "Installing PHP..."
        curl -sSL https://packages.sury.org/php/README.txt | sudo bash
        sudo apt-get update
        sudo apt-get install -y php-fpm php-mysql php-mbstring php-xml php-gd php-pear
        echo "PHP installation completed."
        break
        ;;
    [Nn] | [Nn][Oo])
        echo "Skipping PHP installation."
        break
        ;;
    *)
        echo "Invalid answer. Please enter 'y' for yes or 'n' for no."
        ;;
    esac
done
# == Ondřej Surý PHP Repository for Debian ==

# == Syncthing Debian/Ubuntu ==
while true; do
    read -p "Do you want to install Syncthing? (y/n): " ANSWER
    case $ANSWER in
    [Yy] | [Yy][Ee][Ss])
        install_syncthing() {
            # GPG key:
            sudo mkdir -p /etc/apt/keyrings
            sudo curl -L -o /etc/apt/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
            # Apt sources:
            echo "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable-v2" | sudo tee /etc/apt/sources.list.d/syncthing.list
            printf "Package: *\nPin: origin apt.syncthing.net\nPin-Priority: 990\n" | sudo tee /etc/apt/preferences.d/syncthing.pref
            sudo apt-get update
            sudo apt-get install -y syncthing
        }
        install_syncthing &>/dev/null &
        wait_with_spinner_loading "Installing Syncthing..."
        break
        ;;
    [Nn] | [Nn][Oo])
        echo "Skipping Syncthing installation."
        break
        ;;
    *)
        echo "Invalid answer. Please enter 'y' for yes or 'n' for no."
        ;;
    esac
done
# == Syncthing Debian/Ubuntu ==

# == Docker ==
while true; do
    read -p "Do you want to install Docker? (y/n): " ANSWER
    case $ANSWER in
    [Yy] | [Yy][Ee][Ss])
        install_docker() {
            # Uninstalling old versions
            for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do
                sudo apt-get purge -y $pkg 2>/dev/null
            done
            # Adding Docker's official GPG key:
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc
            # Add the repository to Apt sources:
            echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
                $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
                sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
            sudo apt-get update
            # Installing the Docker packages
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            # Enabling in Systemd so it starts with the system
            sudo systemctl enable docker
        }
        install_docker &>/dev/null &
        wait_with_spinner_loading "Installing Docker..."
        break
        ;;
    [Nn] | [Nn][Oo])
        echo "Skipping Docker installation."
        break
        ;;
    *)
        echo "Invalid answer. Please enter 'y' for yes or 'n' for no."
        ;;
    esac
done
# == Docker ==
